### ISSUE TITLE
Error issuing make command

### ISSUE THREAD

**Issue by astrophysaxist** [IonaKondo/Sample1210#3]
Hi Iona, I get an error running:

```make Up-the-Ramp_test```

I can see in the Makefile that there's a target for it, but the .cpp files referenced in the Makefile are missing from the src directory it seems.

Best,
Greg

**Comment by IonaKondo** [comment]
Thank you for your comment.
I modified the src/Makefile and so on.
So we can compile sample cpp files now as follows.

> cd src
> make SampleProgram3_20201210

Please check if it works.

Best regards,
Iona
