### ISSUE TITLE
S output interpretation

### ISSUE THREAD

**Issue by astrophysaxist** [IonaKondo/Sample1210#5]
Thank you so much for your modifications.
I uploaded 'src/SampleProgram4_20201212.cpp', which outputs a fits file.
I also removed some print statement for the debug.

When I tested by three 5pixels*5pixels sample fits files, which have uniform flux, 1000, 5000, 9000, respectively, the output *S value is 16000.
But if we use CDS by using the first and the end fits files, the output signal is expected to be "9000 - 1000 = 8000".

I think that the outputs of the up-the-ramp is the slope (Signal/T_exposure). 
The up-the-ramp function in Offenberg+2005, seems not to contain the time information.
So how we should treat the output *S value from the Integral function?

_Originally posted by @IonaKondo in https://github.com/IonaKondo/Sample1210/issues/4#issuecomment-743722543_

**Comment by astrophysaxist** [comment]
Hi @IonaKondo  the output `S` is a estimate of the integrated signal.

So, for the frames that have 1000, 5000, 9000 counts the integral is 1000+5000+9000=15000. I think the `Integrate` output is returning 16000 counts because it perhaps expected zero offset (that is it expected the first frame to have 0). If we remove the offset of the first frame (1000) from the Integrate output we get 16000 - 1000 = 15000 as expected.

The `S` output is the slope estimate times the weight, so there is a way to get the slope if we divide by the weight. It looks like the `t` variable in the second `LOOP` of `Integrate` is the weight if you compare the code with the expression in the paper's Figure 1. To get slope you'd divide `S` by `t`. This would give counts per frame. To get counts per second, you would have to divide by the time per frame.

**Comment by IonaKondo** [comment]
Dear Greg,

Thank you for answering.
I did some tests in order to check how *S value changes by input fits files, and uploaded "notes/S_value.txt".
As a result of tests, *S value did not changes by the number of up-the-ramp samples when the difference between the counts of the two consecutive frames is same.

So I think in order to get the counts per frame of the slope estimate times the weight, I need to divide *S by 4.
Because the parameter of Number of shift bits, B=2, quadruple *S value in Integral function.
I do not know why  the parameter, B, is needed.
If you know something, I would like you to let me know.

Best regards,
Iona

**Comment by astrophysaxist** [comment]
Hi @IonaKondo, thanks for reporting back on this. I think I was mistaken before. The output final signal does have a factor of 2**B multiplied and represents the S/W (slope estimate) quantity. The B represents how many extra bits to encode the signal with in order to capture any noise in the lowest significant B bits. So, to recover the slope estimate we only need to shift right B bits. Checkout the updated SampleProgram4 code in my new pull request https://github.com/IonaKondo/Sample1210/pull/7#issue-539002214, and try it out on your different ramp size data.

**Comment by IonaKondo** [comment]
Dear Greg,

Thank you for your pull request and all your help.
I confirmed that the output is the same as the expected slope estimate.
Although I see "Segmentation fault" in the end of the output (I have not find the reason yet), the program is working correctly.
Should we leave the information of Variance (*V) somewhere?
I also confirmed that the value "*V<<B" decreases as the number of the samples of the line-fitting increases.

So, next, I would like to do some tests.
For example, we can check the performance on the PRIME servers, using three 4k*4k sample images.
I'll report when the result comes out.

Best regards,
Iona

**Comment by IonaKondo** [comment]
Dear Greg,

As you know, "segmentation fault" occurs when we free some pointers, because their addresses are different from initial addresses of pointers.
I have checked if there is memory leakage by valgrind when I comment out all "free" operations.
As the result, we do not need to free pointers in the program.

Best regards,
Iona

**Comment by astrophysaxist** [comment]
> Dear Greg,
> 
> Thank you for your pull request and all your help.
> I confirmed that the output is the same as the expected slope estimate.
> Although I see "Segmentation fault" in the end of the output (I have not find the reason yet), the program is working correctly.
> Should we leave the information of Variance (*V) somewhere?
> I also confirmed that the value "*V<<B" decreases as the number of the samples of the line-fitting increases.
> 
> So, next, I would like to do some tests.
> For example, we can check the performance on the PRIME servers, using three 4k*4k sample images.
> I'll report when the result comes out.
> 
> Best regards,
> Iona

Hi Iona, that's good to hear. You could save the variance to create a variance image. The variance should be the error in the signal estimate squared. Having that info might be useful for flagging bad pixels or doing quality control in further analysis. Let's open up another issue about the seg fault.
