### ISSUE TITLE
Segmentation fault on freeing pointer to S, V, ds

### ISSUE THREAD

**Issue by astrophysaxist** [IonaKondo/Sample1210#8]
Dear Greg,

As you know, "segmentation fault" occurs when we free some pointers, because their addresses are different from initial addresses of pointers.
I have checked if there is memory leakage by valgrind when I comment out all "free" operations.
As the result, we do not need to free pointers in the program.

Best regards,
Iona

_Originally posted by @IonaKondo in https://github.com/IonaKondo/Sample1210/issues/5#issuecomment-744302209_

**Comment by astrophysaxist** [comment]
Hi @IonaKondo  I don't get an error when I free S, V, and ds. I'm using g++ version 7.4.0. It's good practice to free dynamically allocated memory to prevent memory leaks. What version of gcc are you using? You can find out by running `g++ --version`

**Comment by astrophysaxist** [comment]
I was able to find the problem here by looking into freeing dynamically allocated memory. We can't free memory from a pointer once it has been incremented. So, we should save a copy of the original pointer from malloc(), then increment a copy. I implemented this in https://github.com/IonaKondo/Sample1210/pull/9#issue-539729136 take a look.

**Comment by IonaKondo** [comment]
Dear Greg,

Thank you for solving the problem. That's very helpful.
I'm using g++ version 4.8.5.
The new program is working properly.

Best regards,
Iona
